export const elements = [
  {
    length: 938,
    width: 300,
    count: 4,
    category: "Kuhinja - gornji dio",
    description: "Vanjski horizontalni elementi",
  },
  {
    length: 830,
    width: 300,
    count: 4,
    category: "Kuhinja - gornji dio",
    description: "Vanjski vertikalni elementi",
  },
  {
    length: 794,
    width: 300,
    count: 2,
    category: "Kuhinja - gornji dio",
    description: "Pregradni vertikalni elementi ",
  },
  {
    length: 458,
    width: 295,
    count: 8,
    category: "Kuhinja - gornji dio",
    description: "Police",
  },
  {
    length: 484,
    width: 830,
    count: 4,
    category: "Kuhinja - gornji dio",
    description: "Vrata 3 rupe za baglame",
  },
  {
    length: 597,
    width: 678,
    count: 1,
    category: "Kuhinja - gornji dio",
    description: "Vrata napa",
  },
  {
    length: 680,
    width: 300,
    count: 2,
    category: "Kuhinja - gornji dio",
    description: "Vertikale napa",
  },
  {
    length: 564,
    width: 300,
    count: 2,
    category: "Kuhinja - gornji dio",
    description: "Horizontale napa",
  },
  {
    length: 562,
    width: 295,
    count: 1,
    category: "Kuhinja - gornji dio",
    description: "Polica napa",
  },
  {
    length: 974,
    width: 830,
    count: 2,
    category: "Kuhinja - gornji dio",
    description: "Ledja",
  },
  {
    length: 680,
    width: 600,
    count: 1,
    category: "Kuhinja - gornji dio",
    description: "Ledja napa",
  },
  {
    length: 760,
    width: 550,
    count: 4,
    category: "Kuhinja - donji dio",
    description: "Vanjski vertikalni element",
  },
  {
    length: 724,
    width: 550,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Pregradni vertikalni element",
  },
  {
    length: 654,
    width: 100,
    count: 2,
    category: "Kuhinja - donji dio",
    description: "Pomocne letve ispod radne ploce ladice",
  },
  {
    length: 654,
    width: 550,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Vanjski horizontalni elementi - ladice",
  },
  {
    length: 614,
    width: 550,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Vanjski horizontalni elementi - sudoper",
  },
  {
    length: 600,
    width: 560,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Postolje ispod sporeta",
  },
  {
    length: 614,
    width: 100,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Zadnja letva vertikalna - sudoper",
  },
  {
    length: 568,
    width: 472,
    count: 3,
    category: "Kuhinja - donji dio",
    description: "Pod za ladice",
  },
  {
    length: 557,
    width: 84,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Ledja za plitku ladicu",
  },
  {
    length: 557,
    width: 199,
    count: 2,
    category: "Kuhinja - donji dio",
    description: "Ledja za duboke ladice",
  },
  {
    length: 678,
    width: 147,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Fronta za plitku ladicu",
  },
  {
    length: 678,
    width: 302,
    count: 2,
    category: "Kuhinja - donji dio",
    description: "Fronte za duboke ladice",
  },
  {
    length: 156,
    width: 757,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Fronta za uski dio",
  },
  {
    length: 488,
    width: 757,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Vrata sudoper",
  },
  {
    length: 690,
    width: 98,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Maska - ladice",
  },
  {
    length: 650,
    width: 98,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Maska - sudoper",
  },
  {
    length: 690,
    width: 760,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Ledja ladice",
  },
  {
    length: 650,
    width: 760,
    count: 1,
    category: "Kuhinja - donji dio",
    description: "Ledja sudoper",
  },
  {
    length: 2404,
    width: 794,
    count: 1,
    category: "Ormar",
    description: "Vrata srednja",
  },
  {
    length: 2404,
    width: 774,
    count: 2,
    category: "Ormar",
    description: "Vrata vanjska",
  },
  {
    length: 776,
    width: 620,
    count: 10,
    category: "Ormar",
    description: "Police",
  },
  {
    length: 2444,
    width: 620,
    count: 2,
    category: "Ormar",
    description: "Vertikalni elementi - pregrade",
  },
  {
    length: 2364,
    width: 720,
    count: 2,
    category: "Ormar",
    description: "Horizontalni elementi - korpus",
  },
  {
    length: 2480,
    width: 720,
    count: 2,
    category: "Ormar",
    description: "Vertikalni elementi - korpus",
  },
  {
    length: 791,
    width: 170,
    count: 2,
    category: "Ormar",
    description: "Ladice - fronte",
  },
  {
    length: 550,
    width: 140,
    count: 4,
    category: "Ormar",
    description: "Ladice - bocni dio",
  },
  {
    length: 716,
    width: 140,
    count: 2,
    category: "Ormar",
    description: "Ladice - zadnji dio",
  },
  {
    length: 752,
    width: 550,
    count: 2,
    category: "Ormar",
    description: "Ladice - pod",
  },
  {
    length: 2100,
    width: 1026,
    count: 1,
    category: "Vjesalica",
    description: "Vertikalni element - ledja",
  },
  {
    length: 486,
    width: 329,
    count: 2,
    category: "Vjesalica",
    description: "Vertikalni elementi - bocni",
  },
  {
    length: 1026,
    width: 347,
    count: 1,
    category: "Vjesalica",
    description: "Horizontalni element - gornji",
  },
  {
    length: 990,
    width: 329,
    count: 1,
    category: "Vjesalica",
    description: "Horizontalni element - donji ",
  },
  {
    length: 990,
    width: 324,
    count: 1,
    category: "Vjesalica",
    description: "Horizontalni element - polica",
  },
  {
    length: 482,
    width: 510,
    count: 2,
    category: "Vjesalica",
    description: "Vrata",
  },
  {
    length: 926,
    width: 347,
    count: 1,
    category: "Vjesalica",
    description: "Horizontalna polica - gornja",
  },
  {
    length: 1014,
    width: 322,
    count: 2,
    category: "Polica",
    description: "Vertikalni elementi - bocni donji",
  },
  {
    length: 1350,
    width: 358,
    count: 2,
    category: "Polica",
    description: "Vertikalni elementi - bocni gornji",
  },
  {
    length: 1332,
    width: 358,
    count: 2,
    category: "Polica",
    description: "Vertikalni elementi - pregrade",
  },
  {
    length: 1170,
    width: 358,
    count: 2,
    category: "Polica",
    description: "Horizontalni elementi - gornji i donji",
  },
  {
    length: 1134,
    width: 358,
    count: 1,
    category: "Polica",
    description: "Horizontalni elementi - srednji",
  },
  {
    length: 1134,
    width: 318,
    count: 5,
    category: "Polica",
    description: "Horizontalni elementi - srednji donji",
  },
  {
    length: 366,
    width: 358,
    count: 8,
    category: "Polica",
    description: "Horizontalne police",
  },
  {
    length: 837,
    width: 582,
    count: 2,
    category: "Polica",
    description: "Vrata",
  },
  {
    length: 166,
    width: 582,
    count: 2,
    category: "Polica",
    description: "Fronta za ladice",
  },
  {
    length: 312,
    width: 115,
    count: 4,
    category: "Polica",
    description: "Ladice - bocni elementi",
  },
  {
    length: 498,
    width: 115,
    count: 2,
    category: "Polica",
    description: "Ladice - ledja",
  },
  {
    length: 322,
    width: 134,
    count: 1,
    category: "Polica",
    description: "Ladice - vertikala za ugradnju mehanizma",
  },
  {
    length: 312,
    width: 534,
    count: 1,
    category: "Polica",
    description: "Ladice - pod",
  },
  {
    length: 482,
    width: 300,
    count: 4,
    category: "Nocni ormaric",
    description: "Vertikalne stranice",
  },
  {
    length: 414,
    width: 300,
    count: 4,
    category: "Nocni ormaric",
    description: "Horizontalne pregrade",
  },
  {
    length: 450,
    width: 320,
    count: 2,
    category: "Nocni ormaric",
    description: "Gronja ploca",
  },
  {
    length: 414,
    width: 120,
    count: 2,
    category: "Nocni ormaric",
    description: "Ledja",
  },
  {
    length: 275,
    width: 390,
    count: 2,
    category: "Nocni ormaric",
    description: "pod ladice",
  },
  {
    length: 447,
    width: 133,
    count: 2,
    category: "Nocni ormaric",
    description: "fronta",
  },
  {
    length: 275,
    width: 80,
    count: 4,
    category: "Nocni ormaric",
    description: "bocni zidovi ladice",
  },
  {
    length: 354,
    width: 80,
    count: 2,
    category: "Nocni ormaric",
    description: "ledja ladice",
  },
];
